package frames;

import listeners.ListenerMenuImagen;
import listeners.ListenerMenuEspacial;
import listeners.ListenerMenuHistograma;
import listeners.ListenerMenuMatriz;
import listeners.ListenerMenuRuido;

/**
 *
 * @author peper
 */
public class JFramePrincipal extends javax.swing.JFrame 
{
    /**
     * @return the JIFM
     */
    public JInternalFrameModificar getJIFM() 
    {
        return JIFM;
    }

    /**
     * @param JIFM the JIFM to set
     */
    public void setJIFM(JInternalFrameModificar JIFM) 
    {
        this.JIFM = JIFM;
    }
    private JInternalFrameGuardarImagen JIFGI;
    
    private JInternalFrameModificar JIFM;
    
    private JInternalFrameCopear JIFC;
    
    private JInternalFrameGraficaHistograma JIFGH;
    private JInternalFrameGraficaHistograma JIFGHE;
    
    private JInternalFrameFiltros JIFFEG;
    private JInternalFrameFiltros JIFFNG;
    private JInternalFrameFiltros JIFFBN;
    private JInternalFrameFiltros JIFFBN2;
    private JInternalFrameFiltros JIFFBNA;
    
    private JInternalFrameMatrizConvolucion JIFMC;
    private JInternalFrameMatrizConvolucion JIFMCK;
    
    private JInternalFrameIluminacion JIFIL;
    
    private JInternalFrameRuidoSP JIFRSP;
    private JInternalFrameRuidoSP JIFRSPB;
    
    //Imagen
    private JInternalFrameImagen JIFI;
    
    public JFramePrincipal() 
    {
        initComponents();
        jMenuItem1.addActionListener(new ListenerMenuImagen(this));
        jMenuItem12.addActionListener(new ListenerMenuImagen(this));
        
        jMenuItem4.addActionListener(new ListenerMenuHistograma(this));
        jMenuItem10.addActionListener(new ListenerMenuHistograma(this));
        
        jMenuItem2.addActionListener(new ListenerMenuEspacial(this));
        jMenuItem3.addActionListener(new ListenerMenuEspacial(this));
        jMenuItem5.addActionListener(new ListenerMenuEspacial(this));
        jMenuItem6.addActionListener(new ListenerMenuEspacial(this));
        jMenuItem7.addActionListener(new ListenerMenuEspacial(this));
        jMenuItem8.addActionListener(new ListenerMenuEspacial(this));
        jMenuItem9.addActionListener(new ListenerMenuEspacial(this));
        jMenuItem_Iluminacion.addActionListener(new ListenerMenuEspacial(this));
        
        jMenuItem11.addActionListener(new ListenerMenuMatriz(this));
        jMenuItem13.addActionListener(new ListenerMenuMatriz(this));
        
        jMenuItem14.addActionListener(new ListenerMenuRuido(this));
        jMenuItem15.addActionListener(new ListenerMenuRuido(this));
        
        JIFI = null;
        
        JIFM = null;
        JIFC = null;
        JIFGH = null;
        JIFGHE = null;
        
        JIFFEG = null;
        JIFFNG = null;
        JIFFBN = null;
        JIFFBN2 = null;
        JIFFBNA = null;
        
        JIFMC = null;
        JIFMCK = null;
        
        JIFIL = null;
        
        JIFGI = null;
        
        JIFRSP = null;
        JIFRSPB = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_AbrirImagen = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu_Modificar = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem_Iluminacion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1245, Short.MAX_VALUE)
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        jMenu_AbrirImagen.setText("Imagen");

        jMenuItem1.setText("Abrir Imagen");
        jMenu_AbrirImagen.add(jMenuItem1);

        jMenuItem12.setText("Guardar Imagen");
        jMenu_AbrirImagen.add(jMenuItem12);

        jMenuBar1.add(jMenu_AbrirImagen);

        jMenu_Modificar.setText("Espacial");

        jMenuItem2.setText("Modificar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu_Modificar.add(jMenuItem2);

        jMenuItem3.setText("Copear pixeles");
        jMenu_Modificar.add(jMenuItem3);

        jMenuItem5.setText("Escala Grises");
        jMenu_Modificar.add(jMenuItem5);

        jMenuItem6.setText("Negativo");
        jMenu_Modificar.add(jMenuItem6);

        jMenuItem7.setText("Blanco y negro");
        jMenu_Modificar.add(jMenuItem7);

        jMenuItem8.setText("Blanco y negro doble U");
        jMenu_Modificar.add(jMenuItem8);

        jMenuItem9.setText("Blanco y negro Umbral Automatico");
        jMenu_Modificar.add(jMenuItem9);

        jMenuItem_Iluminacion.setText("Iluminacion");
        jMenu_Modificar.add(jMenuItem_Iluminacion);

        jMenuBar1.add(jMenu_Modificar);

        jMenu2.setText("Matricez");

        jMenuItem11.setText("Matriz de convolucion");
        jMenu2.add(jMenuItem11);

        jMenuItem13.setText("Matriz de Kirsch");
        jMenu2.add(jMenuItem13);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Histograma");

        jMenuItem4.setText("Grafica Histograma");
        jMenu1.add(jMenuItem4);

        jMenuItem10.setText("Expandir Histograma");
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Ruido");

        jMenuItem14.setText("Sal y Pimienta");
        jMenu3.add(jMenuItem14);

        jMenuItem15.setText("Eliminar ruido");
        jMenu3.add(jMenuItem15);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new JFramePrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem_Iluminacion;
    private javax.swing.JMenu jMenu_AbrirImagen;
    private javax.swing.JMenu jMenu_Modificar;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jDesktopPanePrincipal
     */
    public javax.swing.JDesktopPane getjDesktopPanePrincipal() {
        return jDesktopPanePrincipal;
    }

    /**
     * @param jDesktopPanePrincipal the jDesktopPanePrincipal to set
     */
    public void setjDesktopPanePrincipal(javax.swing.JDesktopPane jDesktopPanePrincipal) {
        this.jDesktopPanePrincipal = jDesktopPanePrincipal;
    }

    /**
     * @return the JIFC
     */
    public JInternalFrameCopear getJIFC() {
        return JIFC;
    }

    /**
     * @param JIFC the JIFC to set
     */
    public void setJIFC(JInternalFrameCopear JIFC) {
        this.JIFC = JIFC;
    }

    /**
     * @return the JIFGH
     */
    public JInternalFrameGraficaHistograma getJIFGH() {
        return JIFGH;
    }

    /**
     * @param JIFGH the JIFGH to set
     */
    public void setJIFGH(JInternalFrameGraficaHistograma JIFGH) 
    {
        this.JIFGH = JIFGH;
    }

    /**
     * @return the JIFI
     */
    public JInternalFrameImagen getJIFI() 
    {
        return JIFI;
    }

    /**
     * @param JIFI the JIFI to set
     */
    public void setJIFI(JInternalFrameImagen JIFI) {
        this.JIFI = JIFI;
    }

    /**
     * @return the JIFFEG
     */
    public JInternalFrameFiltros getJIFFEG() {
        return JIFFEG;
    }

    /**
     * @param JIFFEG the JIFFEG to set
     */
    public void setJIFFEG(JInternalFrameFiltros JIFFEG) {
        this.JIFFEG = JIFFEG;
    }

    /**
     * @return the JIFFNG
     */
    public JInternalFrameFiltros getJIFFNG() {
        return JIFFNG;
    }

    /**
     * @param JIFFNG the JIFFNG to set
     */
    public void setJIFFNG(JInternalFrameFiltros JIFFNG) {
        this.JIFFNG = JIFFNG;
    }

    /**
     * @return the JIFFBN
     */
    public JInternalFrameFiltros getJIFFBN() {
        return JIFFBN;
    }

    /**
     * @param JIFFBN the JIFFBN to set
     */
    public void setJIFFBN(JInternalFrameFiltros JIFFBN) {
        this.JIFFBN = JIFFBN;
    }

    /**
     * @return the JIFIL
     */
    public JInternalFrameIluminacion getJIFIL() {
        return JIFIL;
    }

    /**
     * @param JIFIL the JIFIL to set
     */
    public void setJIFIL(JInternalFrameIluminacion JIFIL) {
        this.JIFIL = JIFIL;
    }

    /**
     * @return the JIFFBN2
     */
    public JInternalFrameFiltros getJIFFBN2() {
        return JIFFBN2;
    }

    /**
     * @param JIFFBN2 the JIFFBN2 to set
     */
    public void setJIFFBN2(JInternalFrameFiltros JIFFBN2) {
        this.JIFFBN2 = JIFFBN2;
    }

    /**
     * @return the JIFFBNA
     */
    public JInternalFrameFiltros getJIFFBNA() {
        return JIFFBNA;
    }

    /**
     * @param JIFFBNA the JIFFBNA to set
     */
    public void setJIFFBNA(JInternalFrameFiltros JIFFBNA) {
        this.JIFFBNA = JIFFBNA;
    }

    /**
     * @return the JIFGHE
     */
    public JInternalFrameGraficaHistograma getJIFGHE() {
        return JIFGHE;
    }

    /**
     * @param JIFGHE the JIFGHE to set
     */
    public void setJIFGHE(JInternalFrameGraficaHistograma JIFGHE) {
        this.JIFGHE = JIFGHE;
    }

    /**
     * @return the JIFMC
     */
    public JInternalFrameMatrizConvolucion getJIFMC() {
        return JIFMC;
    }

    /**
     * @param JIFMC the JIFMC to set
     */
    public void setJIFMC(JInternalFrameMatrizConvolucion JIFMC) {
        this.JIFMC = JIFMC;
    }

    /**
     * @return the jMenuItem11
     */
    public javax.swing.JMenuItem getjMenuItem11() {
        return jMenuItem11;
    }

    /**
     * @param jMenuItem11 the jMenuItem11 to set
     */
    public void setjMenuItem11(javax.swing.JMenuItem jMenuItem11) 
    {
        this.jMenuItem11 = jMenuItem11;
    }

    /**
     * @return the JIFGI
     */
    public JInternalFrameGuardarImagen getJIFGI() 
    {
        return JIFGI;
    }

    /**
     * @param JIFGI the JIFGI to set
     */
    public void setJIFGI(JInternalFrameGuardarImagen JIFGI) 
    {
        this.JIFGI = JIFGI;
    }

    /**
     * @return the JIFMCK
     */
    public JInternalFrameMatrizConvolucion getJIFMCK() {
        return JIFMCK;
    }

    /**
     * @param JIFMCK the JIFMCK to set
     */
    public void setJIFMCK(JInternalFrameMatrizConvolucion JIFMCK) {
        this.JIFMCK = JIFMCK;
    }

    /**
     * @return the JIFRSP
     */
    public JInternalFrameRuidoSP getJIFRSP() {
        return JIFRSP;
    }

    /**
     * @param JIFRSP the JIFRSP to set
     */
    public void setJIFRSP(JInternalFrameRuidoSP JIFRSP) {
        this.JIFRSP = JIFRSP;
    }

    /**
     * @return the JIFRSPB
     */
    public JInternalFrameRuidoSP getJIFRSPB() {
        return JIFRSPB;
    }

    /**
     * @param JIFRSPB the JIFRSPB to set
     */
    public void setJIFRSPB(JInternalFrameRuidoSP JIFRSPB) {
        this.JIFRSPB = JIFRSPB;
    }
}
