package frames;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author peper
 */
public class JInternalFrameCopear extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameCopear
     */
    private JInternalFrameImagen JFI;
    private JFramePrincipal JFP;
    private BufferedImage bufferimagen;
    
    public JInternalFrameCopear(JFramePrincipal JFP) 
    {
        this.JFP = JFP;
        this.JFI = JFP.getJIFI();
        initComponents();
        
        this.jButton_Copear.addActionListener(new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent ae) 
            {
                buttCopear();
            }
        });
        
        this.jButton_Pegar.addActionListener(new ActionListener() 
        {
            
            @Override
            public void actionPerformed(ActionEvent ae) 
            {
                buttPegar();
            }
        });
        
        addInternalFrameListener(new InternalFrameAdapter(){
            public void internalFrameClosing(InternalFrameEvent e) 
            {
                JFP.setJIFC(null);
            }
        });
    }
    
    public void buttCopear()
    {
        BufferedImage aux = herramientas.herramientas.toBufferedImage(this.JFI.getImagenSecundaria());
        int x = Integer.parseInt(jTextField_x.getText());
        int y = Integer.parseInt(jTextField_y.getText());
        int t = Integer.parseInt(jTextField_T.getText());
        Color col = Color.WHITE;
        bufferimagen = new BufferedImage(t, t, 1);

        for(int xx = 0; xx < t; xx++)
        {
            for(int yy = 0; yy < t; yy++)
            {
                bufferimagen.setRGB(xx, yy, aux.getRGB(x+xx, y+yy));
            }
        }

        Image aux2 = herramientas.herramientas.toImage(bufferimagen);
    }
    
    public void buttPegar()
    {
        BufferedImage aux = herramientas.herramientas.toBufferedImage(this.JFI.getImagenSecundaria());
        int x = Integer.parseInt(jTextField_x.getText());
        int y = Integer.parseInt(jTextField_y.getText());
        int t = Integer.parseInt(jTextField_T.getText());

        for(int xx = 0; xx < t; xx++)
        {
            for(int yy = 0; yy < t; yy++)
            {
                aux.setRGB(xx + x, yy + y, bufferimagen.getRGB(xx, yy));
            }
        }

        actualizarImagen(aux);
    }
    
    public void actualizarImagen (BufferedImage aux)
    {
        this.JFI.setImagen(herramientas.herramientas.toImage(aux));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_x = new javax.swing.JTextField();
        jTextField_y = new javax.swing.JTextField();
        jButton_Pegar = new javax.swing.JButton();
        jButton_Copear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_T = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 51, 255));
        setClosable(true);
        setIconifiable(true);

        jButton_Pegar.setText("Pegar");
        jButton_Pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PegarActionPerformed(evt);
            }
        });

        jButton_Copear.setText("Copear");
        jButton_Copear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CopearActionPerformed(evt);
            }
        });

        jLabel1.setText("X");

        jLabel2.setText("y");

        jLabel3.setText("Tamaño");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_x, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_y, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_T, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Copear, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Pegar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_T, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_x, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_y, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Copear, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Pegar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_PegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PegarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_PegarActionPerformed

    private void jButton_CopearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CopearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CopearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Copear;
    private javax.swing.JButton jButton_Pegar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField_T;
    private javax.swing.JTextField jTextField_x;
    private javax.swing.JTextField jTextField_y;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the JFI
     */
    public JInternalFrameImagen getJFI() {
        return JFI;
    }

    /**
     * @param JFI the JFI to set
     */
    public void setJFI(JInternalFrameImagen JFI) {
        this.JFI = JFI;
    }
}
